basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.BasketSummeryView.as_view(), name='basket_summery'),
    path('add', views.AddToBasketView.as_view(), name='add_to_basket'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('store/', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('order/', include('order.urls', namespace='order')),
    path('search', include('search.urls', namespace='search')),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, re_path
from . import views


app_name = 'store'
urlpatterns = [
    path('', views.IndexFormView.as_view(), name='p_search'),
    path('product-list', views.ProductListView.as_view(), name='product_list'),
    re_path('product-list/(?P<category>[-\w]+)', views.ProductListView.as_view(), name='product_list_cat'),
    re_path(r'product/(?P<slug>[-\w]+)', views.ProductDetail.as_view(), name='product_detail'),
]

store/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey('category', on_delete=models.SET_NULL, null=True, related_name='products')
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    img = models.ImageField(upload_to='product_images/%Y/%m/%d/', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    sex = models.CharField(
        choices=(
            ('0', 'زن'),
            ('1', 'مرد'),
        ),
        max_length=1,
        default='0',
    )
    age_min = models.PositiveIntegerField(default=settings.MIN_PRODUCT_AGE, validators=[MinValueValidator(settings.MIN_PRODUCT_AGE)])
    age_max = models.PositiveIntegerField(default=settings.MAX_PRODUCT_AGE, validators=[MaxValueValidator(settings.MAX_PRODUCT_AGE)])
    height_min = models.PositiveIntegerField(default=settings.MIN_PRODUCT_HEIGHT, validators=[MinValueValidator(settings.MIN_PRODUCT_HEIGHT)])
    height_max = models.PositiveIntegerField(default=settings.MAX_PRODUCT_HEIGHT, validators=[MaxValueValidator(settings.MAX_PRODUCT_HEIGHT)])
    weight_min = models.PositiveIntegerField(default=settings.MIN_PRODUCT_WEIGHT, validators=[MinValueValidator(settings.MIN_PRODUCT_WEIGHT)])
    weight_max = models.PositiveIntegerField(default=settings.MAX_PRODUCT_WEIGHT, validators=[MaxValueValidator(settings.MAX_PRODUCT_WEIGHT)])
    price = models.IntegerField(default=0)
    in_stock = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-updated',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

store/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.conf import settings


class PersonalizeForm(forms.Form):
    sex = forms.ChoiceField(
        choices=(
            ('0', 'زن'),
            ('1', 'مرد'),
        ),
        label='جنسیت',
        widget=forms.Select(
            attrs={
                'placeholder': 'Name', 'style': 'text-align-last:center;', 'class': 'form-control'
            }
        )
    )

    age = forms.IntegerField(label='سن', widget=forms.NumberInput(attrs={'placeholder': 'سن', 'class':'form-control'}))

    height = forms.IntegerField(label='قد', widget=forms.NumberInput(attrs={'placeholder': 'قد', 'class':'form-control'}))

    weight = forms.IntegerField(label='وزن', widget=forms.NumberInput(attrs={'placeholder': 'وزن', 'class':'form-control'}))

    def clean_age(self):
        age = self.cleaned_data['age']
        if not (settings.MIN_PRODUCT_AGE < age <= settings.MAX_PRODUCT_AGE):
            raise ValidationError('حداقل سن مجاز 13 می باشد')
        return age

    def clean_height(self):
        height = self.cleaned_data['height']
        if not (settings.MIN_PRODUCT_HEIGHT < height <= settings.MAX_PRODUCT_HEIGHT):
            raise ValidationError('حداقل قد مجاز 100 می باشد')
        return height

    def clean_weight(self):
        weight = self.cleaned_data['weight']
        if not (settings.MIN_PRODUCT_WEIGHT < weight <= settings.MAX_PRODUCT_WEIGHT):
            raise ValidationError('حداقل وزن مجاز 30 می باشد')
        return weight

store/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.views import View
from django.views.generic import ListView, FormView
from django.core.paginator import Paginator
from .forms import PersonalizeForm
from .models import Product, Category


class IndexFormView(FormView):
    template_name = 'store/index.html'
    form_class = PersonalizeForm

    def get_success_url(self):
        form_data = self.request.POST
        sex = form_data['sex']
        age = form_data['age']
        height = form_data['height']
        weight = form_data['weight']
        url = f'product-list?sex={sex}&age={age}&height={height}&weight={weight}'
        return url


class ProductListView(ListView):
    model = Product
    paginate_by = 6
    page_kwarg = 'page'
    template_name = 'store/product_list.html'


    def get_queryset(self):
        if category_slug := self.kwargs.get('category'):
            category = get_object_or_404(Category, slug=category_slug)
            products = category.products.all()
            return products
        if self.request.GET.get('sex'):
            q = self.request.GET
            return get_list_or_404(
                Product,
                sex=q['sex'],
                age_max__gte=q['age'],
                age_min__lte=q['age'],
                height_max__gte=q['height'],
                height_min__lte=q['height'],
                weight_max__gte=q['weight'],
                weight_min__lte=q['weight'],

            )
        return super().get_queryset()


class ProductDetail(View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        return render(request, 'store/product_detail.html', {'product': product})

store/templates/store/index.html
{% extends 'base.html' %}
{% load static %}

{% block custom_head %}
    <link rel="stylesheet" href="{% static 'store/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/style.css' %}">
{% endblock custom_head %}

{% block body %}
<div class="wrapper" style="background-image: url({% static 'store/images/bg-registration-form-1.jpg' %});">
    <div class="inner">
        <div class="image-holder">
            <img src="{% static 'store/images/registration-form-1.jpg' %}" alt="">
        </div>
        <form method="post">
            {% csrf_token %}
            <h3>جست و جو محصول مناسب شما</h3>
            {% for field in form %}
                <div class="form-wrapper">
                    {{ field.errors }}
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit">
                <i class="zmdi zmdi-arrow-right"></i>
            </button>
        </form>
    </div>
</div>
{% endblock body %}

store/templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}



{% block body %}

    <section class="u-align-center u-clearfix u-section-2" id="sec-4496">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1"><!--product--><!--product_options_json--><!--{"source":""}--><!--/product_options_json--><!--product_item-->
        <div class="u-container-style u-expanded-width u-product u-product-1">
          <div class="u-container-layout u-valign-middle-lg u-valign-middle-xl u-valign-top-sm u-valign-top-xs u-container-layout-1"><!--product_image-->
            <img alt="" class="u-expanded-width-sm u-expanded-width-xs u-image u-image-default u-product-control u-image-1" src="{{ product.img.url }}"><!--/product_image-->
            <div class="u-align-center-sm u-align-center-xs u-align-left-lg u-align-left-md u-align-left-xl u-container-style u-expanded-width-sm u-expanded-width-xs u-group u-shape-rectangle u-group-1" style="text-align:right;">
              <div class="u-container-layout u-valign-middle u-container-layout-2">
                <div class="u-border-3 u-border-palette-4-base u-line u-line-horizontal u-line-1"></div><!--product_title-->
                <h2 class="u-custom-font u-font-merriweather u-product-control u-text u-text-1">
                  {{product.name}}
                </h2><!--/product_title--><!--product_price-->
                <div class="u-custom-font u-font-merriweather u-product-control u-product-price u-product-price-1">
                  <div class="u-price-wrapper u-spacing-10"><!--product_old_price-->
                    <div class="u-hide-price u-old-price" style="text-decoration: line-through !important;" wfd-invisible="true"><!--product_old_price_content-->$12<!--/product_old_price_content--></div><!--/product_old_price--><!--product_regular_price-->
                    <div dir="ltr" class="u-price u-text-palette-4-base" style="font-size: 1.5rem; font-weight: 700;"><!--product_regular_price_content-->{{ product.price|floatformat:"-3g" }} T<!--/product_regular_price_content--></div><!--/product_regular_price-->
                  </div>
                </div><!--/product_price--><!--product_content-->
                <div class="u-product-control u-product-desc u-text u-text-default u-text-2"><!--product_content_content-->
                  <p>{{ product.description }}</p><!--/product_content_content-->
                </div><!--/product_content--><!--product_button--><!--options_json--><!--{"clickType":"add-to-cart"}--><!--/options_json-->
                <a href="#" onclick="add_to_cart()" class="u-btn u-button-style u-hover-grey-75 u-palette-4-base u-product-control u-btn-1"><!--product_button_content-->اضافه به سبد<!--/product_button_content--></a><!--/product_button-->
              </div>
            </div>
          </div>
        </div><!--/product_item--><!--/product-->
        </p>
      </div>
    </section>


{% endblock body %}

{% block custom_html %}
<script>
        function add_to_cart(){
                $.ajax({
                    type: 'POST',
                    url:'{% url 'basket:add_to_basket' %}',
                    data:{
                        product_id:{{product.id}},
                        csrfmiddlewaretoken:"{{csrf_token}}",
                    },
                    success:function(json){
                        alert('به سبد اضافه شد');
                    },
                    error:function(xhr, errmsg, err){}

                })
        }
</script>
{% endblock custom_html %}

store/templates/store/product_list.html
{% extends 'base.html' %}
{% load static %}
{% load store_extra %}


{% block body %}
<!-- sidebar + content -->
<section >
  <div class="container">
    <div class="row">
      <!-- sidebar -->

      <!-- sidebar -->
      <!-- content -->
      <div class="col-lg-9">

        <div style="min-height: 500px;margin-top:10px;">
          <h4>محصولات مناسب شما:</h4>

        {% for product in page_obj %}
          <div class="row justify-content-center mb-3">
          <div class="col-md-12">
            <div class="card shadow-0 border rounded-3">
              <div class="card-body">
                <a href="{{ product.get_absolute_url }}" style="color: inherit;">
                <div class="row g-0">
                  <div class="col-xl-3 col-md-4 d-flex justify-content-center">
                    <div class="bg-image hover-zoom ripple rounded ripple-surface me-md-3 mb-3 mb-md-0">
                      <img src="{% if product.img %}{{ product.img.url }}{% endif %}" alt="image" style="padding:5px;" class="w-100">
                        <div class="hover-overlay">
                          <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
                        </div>
                    </div>

                  </div>
                  <div class="col-xl-6 col-md-5 col-sm-7">
                    <h5>{{product.name}}</h5>
                    <p class="text mb-4 mb-md-0">
                      {{product.description}}
                    </p>
                  </div>
                  <div class="col-xl-3 col-md-3 col-sm-5">
                    <div class="d-flex flex-row align-items-center mb-1">
                      <h4 class="mb-1 me-1">{{product.price|floatformat:"-3g"}}T</h4>
                    </div>
                  </div>
                </div>
                  </a>
              </div>
            </div>
          </div>
        </div>
        {% empty %}
          <div class="row justify-content-center mb-3">
          <div class="col-md-12">
            <div class="card shadow-0 border rounded-3">
              <div class="card-body">
                <div class="row g-0">
                  <div class="col-xl-3 col-md-4 d-flex justify-content-center">
                    <div class="bg-image hover-zoom ripple rounded ripple-surface me-md-3 mb-3 mb-md-0">
                      <img src="{% static 'store/images/pngtree-not-found-outline-icon-vectors-png-image_1737857.jpg' %}" class="w-100">
                      <a href="#!">
                        <div class="hover-overlay">
                          <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
                        </div>
                      </a>
                    </div>
                  </div>
                  <div class="col-xl-6 col-md-5 col-sm-7">
                    <h5>محصولی پیدا نشد</h5>

                    <p class="text mb-4 mb-md-0">
                      ممکن است اطلاعات را اشتباه وارد کرده باشید یا در حال حاضر محصولی مناسب شما وجود ندارد.
                    </p>
                  </div>
                  <div class="col-xl-3 col-md-3 col-sm-5">

                    <div class="mt-4">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
          </div>


        <hr>

        <!-- Pagination -->
        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
          {% if page_obj.has_other_pages %}
            <ul class="pagination">
              {% if page_obj.has_previous %}
              <li class="page-item active">
                <a class="page-link" href="{{ request.get_full_path  | update_path_page:page_obj.previous_page_number}}" aria-label="Previous">
                  <span aria-hidden="true">«</span>
                </a>
              </li>
              {% endif %}
              <li class="page-item active"><a class="page-link" href="#">{{page_obj.number}}</a></li>
              {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="{{ request.get_full_path  | update_path_page:page_obj.next_page_number}}" aria-label="Next">
                  <span aria-hidden="true">»</span>

                </a>

              </li>
              {% endif %}

            </ul>
          {% endif %}
        </nav>

        <!-- Pagination -->
      </div>
    </div>
  </div>
</section>

{% block custom_html %}
<script src="{% static 'store/js/mdb.min.js' %}"></script>
<script type="text/javascript" src="{% static 'store/js/mdb-plugins-gathered.min.js' %}"></script>
{% endblock custom_html %}
{% endblock body %}