basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.BasketSummeryView.as_view(), name='basket_summery'),
    path('add', views.AddToBasketView.as_view(), name='add_to_basket'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('store/', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('order/', include('order.urls', namespace='order')),
    path('search', include('search.urls', namespace='search')),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
]

store/urls.py
from django.urls import path, re_path
from . import views


app_name = 'store'
urlpatterns = [
    path('', views.IndexFormView.as_view(), name='p_search'),
    path('product-list', views.ProductListView.as_view(), name='product_list'),
    re_path('product-list/(?P<category>[-\w]+)', views.ProductListView.as_view(), name='product_list_cat'),
    re_path(r'product/(?P<slug>[-\w]+)', views.ProductDetail.as_view(), name='product_detail'),
]

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views import View
from django.views.generic import TemplateView
from .basket import Basket
from store.models import Product



class BasketSummeryView(TemplateView):
    template_name = "basket/basket.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'personal' in self.request.session:
            context['personal'] = self.request.session['personal']
        return context

class AddToBasketView(View):
    def post(self, request):
        basket = Basket(request)
        product = get_object_or_404(Product, id=request.POST['product_id'])
        basket.add(product, 1)
        response = JsonResponse({'msg': 'به سبد خرید اضافه شد'}, status=201)
        return response

basket/templates/basket/basket.html
{% extends 'base.html' %}
{% load static %}

{% block custom_head %}
    <link rel="stylesheet" href="{% static 'basket/css/basket.css' %}">
{% endblock custom_head %}

{% block body %}

    <div class="container px-3 my-5 clearfix">
    <!-- Shopping cart table -->
    <div class="card">
        <div class="card-header">
            <h2>سبد خرید</h2>
        </div>
        <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered m-0">
                <thead>
                  <tr>
                    <!-- Set columns width -->
                    <th class="text-center py-3 px-4" style="min-width: 400px;">محصولات</th>
                    <th class="text-right py-3 px-4" style="width: 100px;">قیمت</th>
                    <th class="text-center py-3 px-4" style="width: 120px;">تعداد</th>
                    <th class="text-right py-3 px-4" style="width: 100px;">کل</th>
<!--                    <th class="text-center align-middle py-3 px-0" style="width: 40px;"><a href="#" class="shop-tooltip float-none text-light" title="" data-original-title="Clear cart"><i class="ino ion-md-trash"></i></a></th>-->
                  </tr>
                </thead>
                <tbody>
                  {% for item in basket %}
                    <tr>
                      <td class="p-4">
                        <div class="media align-items-center">
                          <img src="{{item.product.img.url}}" class="d-block ui-w-40 ui-bordered mr-4" alt="">
                          <div class="media-body">
                            <a href="{{item.product.get_absolute_url}}" class="d-block text-dark">{{item.product.name}}</a>
                            <small>
                              <span class="text-muted">{{item.product.description|truncatechars:45}}</span>

                            </small>
                          </div>
                        </div>
                      </td>
                      <td class="text-right font-weight-semibold align-middle p-4">{{item.product.price|floatformat:"-3g"}}</td>
                      <td class="text-center font-weight-semibold align-middle p-4">{{item.qty}}</td>
                      <td class="text-right font-weight-semibold align-middle p-4">{{item.total_price|floatformat:"-3g"}}</td>
<!--                      <td class="text-center align-middle px-0"><a href="#" class="shop-tooltip close float-none text-danger" title="" data-original-title="Remove">×</a></td>-->
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- / Shopping cart table -->

            <div class="d-flex flex-wrap justify-content-between align-items-center pb-4">
              <div class="d-flex">
                <div class="text-right mt-4">
                  <label class="text-muted font-weight-normal m-0">جمع کل</label>
                  <div class="text-large"><strong>{{basket.total_price|floatformat:"-3g"}}T</strong></div>
                </div>
              </div>
            </div>

            <div class="row float-right">
              <div class="col-5">
                  {% if personal.values  %}
                        <a href="{% url 'store:product_list' %}?sex={{personal.values.sex}}&age={{personal.values.age}}&height={{personal.values.height}}&weight={{personal.values.weight}}">
                    {% else %}
                        <a href="/">
                  {% endif %}
                <h4 type="button" class="btn btn-lg btn-primary mt-2">ادامه خرید</h4>
                </a>
              </div>
              <div class="col-6">
              <a href="{% url 'order:checkout' %}">
              <button type="button" class="btn btn-lg btn-primary mt-2">ثبت سفارش</button>
                </a>
              </div>
            </div>

          </div>
      </div>
  </div>

{% endblock body %}