basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.BasketSummeryView.as_view(), name='basket_summery'),
    path('add', views.AddToBasketView.as_view(), name='add_to_basket'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('store/', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('order/', include('order.urls', namespace='order')),
    path('search', include('search.urls', namespace='search')),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

app_name = 'serach'

urlpatterns = [
    path('', views.SearchView.as_view(), name='search'),
]

store/urls.py
from django.urls import path, re_path
from . import views


app_name = 'store'
urlpatterns = [
    path('', views.IndexFormView.as_view(), name='p_search'),
    path('product-list', views.ProductListView.as_view(), name='product_list'),
    re_path('product-list/(?P<category>[-\w]+)', views.ProductListView.as_view(), name='product_list_cat'),
    re_path(r'product/(?P<slug>[-\w]+)', views.ProductDetail.as_view(), name='product_detail'),
]

templates/inc/header.html
{% load static %}
<header>
<!-- Jumbotron -->
    <nav class="navbar navbar-expand navbar-dark bg-primary">
     <a class="navbar-brand" href="/">STORE</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              دسته بندی ها
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              {% for cat in categories %}
                <a class="dropdown-item" href="{% url 'store:product_list_cat' cat.slug %}">{{cat.name}}</a>
              {% endfor %}
            </div>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'store:p_search' %}">جست و جوی شخصی<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'basket:basket_summery' %}">سبد خرید<span class="sr-only">(current)</span></a>
          </li>

        </ul>
      </div>
            <form class="form-inline" action="{% url 'search:search' %}">
        <div class="input-group rounded">
          <input type="search" name="q" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
        </div>
      </form>


    </nav>

<!-- Heading -->
</header>

templates/inc/store_head.html
{% load static %}
    <link rel="stylesheet" href="{% static 'store/css/nicepage.css' %}" media="screen">
<!--    <script class="u-script" type="text/javascript" src="//static.nicepage.com/shared/assets/jquery-1.9.1.min.js" defer=""></script>-->
    <script class="u-script" type="text/javascript" src="{% static 'store/js/nicepage.js' %}" defer=""></script>
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Merriweather:300,300i,400,400i,700,700i,900,990i|Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
    <style class="u-style">.u-section-2 .u-sheet-1 {min-height: 730px}
.u-section-2 .u-product-1 {min-height: 574px; height: auto; margin: 60px auto 0 0}
.u-section-2 .u-container-layout-1 {padding: 30px 0 30px 30px}
.u-section-2 .u-image-1 {width: 540px; height: 514px; margin: 0 auto 0 0}
.u-section-2 .u-group-1 {width: 512px; min-height: 514px; margin: -514px 0 0 auto}
.u-section-2 .u-container-layout-2 {padding: 30px}
.u-section-2 .u-line-1 {width: 43px; height: 3px; transform-origin: left center; margin: 0 auto 0 0}
.u-section-2 .u-text-1 {font-size: 3rem; font-weight: 700; margin: 20px 60px 0 0}
.u-section-2 .u-product-price-1 {margin: 22px auto 0 0}
.u-section-2 .u-text-2 {font-weight: 700; font-size: 1.125rem; margin: 18px auto 0 0}
.u-section-2 .u-btn-1 {border-style: none; letter-spacing: 3px; background-image: none; text-transform: uppercase; font-weight: 400; margin: 28px auto 0 0; padding: 10px 65px}
.u-section-2 .u-text-3 {font-family: Poppins; margin: 11px auto 60px}
.u-section-2 .u-btn-2 {border-style: none none solid; padding: 0}
@media (max-width: 1199px){ .u-section-2 .u-sheet-1 {min-height: 730px}
.u-section-2 .u-product-1 {margin-right: initial; margin-left: initial}
.u-section-2 .u-image-1 {width: 440px}
.u-section-2 .u-group-1 {width: 470px}
.u-section-2 .u-container-layout-2 {padding-left: 40px}
.u-section-2 .u-line-1 {width: 43px}
.u-section-2 .u-text-1 {margin-right: 0} }
@media (max-width: 991px){ .u-section-2 .u-sheet-1 {min-height: 638px}
.u-section-2 .u-product-1 {min-height: 477px; margin-right: initial; margin-left: initial}
.u-section-2 .u-image-1 {width: 330px; height: 417px}
.u-section-2 .u-group-1 {width: 360px; min-height: 417px; margin-top: -417px}
.u-section-2 .u-text-1 {font-size: 2.25rem}
.u-section-2 .u-text-3 {width: auto; margin-top: 16px} }
@media (max-width: 767px){ .u-section-2 .u-sheet-1 {min-height: 948px}
.u-section-2 .u-product-1 {min-height: 836px; margin-top: 30px; margin-right: initial; margin-left: initial}
.u-section-2 .u-container-layout-1 {padding-left: 0}
.u-section-2 .u-image-1 {height: 458px; margin-right: initial; margin-left: initial; width: auto}
.u-section-2 .u-group-1 {min-height: 318px; margin-top: 0; margin-right: initial; margin-left: initial; width: auto}
.u-section-2 .u-container-layout-2 {padding-right: 0; padding-left: 10px}
.u-section-2 .u-line-1 {margin-left: auto}
.u-section-2 .u-product-price-1 {margin-left: auto}
.u-section-2 .u-text-2 {margin-right: 0}
.u-section-2 .u-btn-1 {margin-left: auto}
.u-section-2 .u-text-3 {margin-top: 16px; margin-bottom: 30px} }
@media (max-width: 575px){ .u-section-2 .u-text-1 {font-size: 1.5rem} }</style>